---
- name: Commono role for all servers
  become: yes
  remote_user: "{{ remote_user }}"
  hosts: all
  tasks:
    - name: Install docker
      include_role:
        name: geerlingguy.docker

    - name: Install python tools
      apt:
        name: ['python3-pip', 'python3-setuptools']
        state: present

    - name: Install pip modules
      pip:
        name:
          - docker >= 5.0.0
          - 